version: '3'
services:
  migrator:
    image: golang
    user: 1000:1000
    volumes:
      - .:/usr/src/migrator
      - go_pkg:/go/pkg
    working_dir: /usr/src/migrator
    hostname: migrator
    entrypoint: ./docker/dev-entrypoint.sh
    environment:
      GOCACHE: /usr/src/migrator/.cache/go-build
  mysql:
    image: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgres/data
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
volumes:
  mysql_data:
  postgres_data:
  go_pkg: