version: '3'
services:
  migrator:
    image: golang
    platform: linux/amd64
    volumes:
      - .:/usr/src/migrator
      - ./entrypoint.sh:/usr/src/migrator/entrypoint.sh
      - go_pkg:/go/pkg
    working_dir: /usr/src/migrator
    entrypoint: ./entrypoint.sh
    environment:
      SRC_DIR: /usr/src/migrator
  mysql:
    image: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgres/data
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
volumes:
  mysql_data:
  postgres_data:
  go_pkg: