CREATE TABLE IF NOT EXISTS migrations (
    id AUTO INCREMENT PRIMARY KEY NOT NULL UNSIGNED INDEX,
    key VARCHAR(128) NOT NULL INDEX,
    datatime DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS migrations_lock (
    id TINYINT NOT NULL UNIQUE CHECK (id = 1),
    is_locked BOOLEAN NOT NULL DEFAULT 0
);