FROM guilhermewebdev/migrator:build as build
FROM debian:stable-slim
RUN apt-get update && apt-get install -y default-mysql-client postgresql-client sqlite3 && rm -rf /var/lib/apt/lists/*
COPY --from=build /migrator/bin/migrate /bin/migrate
RUN groupadd --gid 1000 migrator && \
    useradd -Mr --uid 1000 --gid 1000 -s /bin/bash migrator
USER migrator