FROM migrator:build as build
RUN echo "migrator:x:1000:1000::/:/migrate" > /etc/passwd_migrator
FROM scratch
COPY --from=build /lib64/ld-linux-x86-64.so.2 /lib64/ld-linux-x86-64.so.2
COPY --from=build /lib/x86_64-linux-gnu/libc.so.6 /lib/x86_64-linux-gnu/libc.so.6
COPY --from=build /migrator/bin/migrate /migrate
COPY --from=build /etc/passwd_migrator /etc/passwd
ENTRYPOINT [ "/migrate" ]
USER migrator