FROM guilhermewebdev/migrator:build as build
FROM alpine
COPY --from=build /migrator/bin/migrate /bin/migrate
RUN addgroup -S -g 1000 migrator && \
    adduser -SHD -s /bin/sh -u 1000 -G migrator migrator
USER migrator