baseURL = 'http://example.org/'
title = 'Migrator'
theme = 'chalk'
enableRobotsTXT = true

[languages]
  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-us'
    languageName = 'English'
  [languages.pt-br]
    contentDir = 'content/pt-br'
    disabled = false
    languageCode = 'pt-br'
    languageName = 'Português Brasil'

[params]
  version = "0.1"