name: Docker Build and Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    needs: tests

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-docker@v2
      with:
        dockerfile: ./docker/Dockerfile.build

    - name: Build Docker Images
      run: |
        docker build -t migrator:build -f docker/Dockerfile.build .
        docker build -t migrator:alpine -f docker/Dockerfile.alpine .
        docker build -t migrator:bullseye -t migrator:latest -f docker/Dockerfile.bullseye .
        docker build -t migrator:scratch -f docker/Dockerfile.scratch .
        docker build -t migrator:bookworm -f docker/Dockerfile.bookworm .
        docker build -t migrator:debian -f docker/Dockerfile.debian .
        docker build -t migrator:slim -f docker/Dockerfile.slim .

    - name: Push Docker Images
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push migrator:build
        docker push migrator:alpine
        docker push migrator:bullseye
        docker push migrator:latest
        docker push migrator:scratch
        docker push migrator:bookworm
        docker push migrator:debian
        docker push migrator:slim

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - name: Set up Docker
      uses: docker/setup-docker@v2
      with:
        dockerfile: ./docker/Dockerfile.build

    - name: Publish Docker Images on Tag
      run: |
        version=$(echo "${{ github.ref }}" | sed 's/refs\/tags\///')
        docker tag migrator:build ${{ secrets.DOCKER_USERNAME }}/migrator:$version
        docker tag migrator:alpine ${{ secrets.DOCKER_USERNAME }}/migrator:alpine-$version
        docker tag migrator:bullseye ${{ secrets.DOCKER_USERNAME }}/migrator:bullseye-$version
        docker tag migrator:latest ${{ secrets.DOCKER_USERNAME }}/migrator:latest-$version
        docker tag migrator:scratch ${{ secrets.DOCKER_USERNAME }}/migrator:scratch-$version
        docker tag migrator:bookworm ${{ secrets.DOCKER_USERNAME }}/migrator:bookworm-$version
        docker tag migrator:debian ${{ secrets.DOCKER_USERNAME }}/migrator:debian-$version
        docker tag migrator:slim ${{ secrets.DOCKER_USERNAME }}/migrator:slim-$version
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push ${{ secrets.DOCKER_USERNAME }}/migrator:$version
        docker push ${{ secrets.DOCKER_USERNAME }}/migrator:alpine-$version
        docker push ${{ secrets.DOCKER_USERNAME }}/migrator:bullseye-$version
        docker push ${{ secrets.DOCKER_USERNAME }}/migrator:latest-$version
        docker push ${{ secrets.DOCKER_USERNAME }}/migrator:scratch-$version
        docker push ${{ secrets.DOCKER_USERNAME }}/migrator:bookworm-$version
        docker push ${{ secrets.DOCKER_USERNAME }}/migrator:debian-$version
        docker push ${{ secrets.DOCKER_USERNAME }}/migrator:slim-$version
